using Microsoft.EntityFrameworkCore.Migrations;

namespace TheatersIS.DataLayer.Migrations
{
    public partial class FillVariantsTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (1, N'Трагедия')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (1, N'Фьяба')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (1, N'Опера')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (1, N'Танцевальное шоу')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (1, N'Балетная сюита')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (1, N'Сказка')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (1, N'Концерт')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (1, N'Мюзикл')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (1, N'Пьеса')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Фантасмагория')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Мелодрама')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Роман')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Оперетта')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Драма')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Спектакль')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Лирическая феерия')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Сатирическая комедия')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Спектакль-притча')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Комедия')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Детектив')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Рок-опера')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 1, N'Научная фантастика')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Лазарева С. В.')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Карло Гоцци')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Пьер Бомарше')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Льюис Кэрролл')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Алекскей Николаевич Толстой')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Григорий Израилевич Горин')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Евгений Васильевич Клюев')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Вера Добрая')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Дмитрий Михайлович Липскеров')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Альфред Грюнвальд')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Мора Йокаи')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Николай Носов')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Ханс Кристиан Андерсен')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Николай Гуриевич Кулиш')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Мольер')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Уильям Сароян')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Иван Яковлевич Франко')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Уильям Шекспир')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Александр Валентинович Вампилов')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Агата Кристи')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Антуан де Сент-Экзюпери')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Эрик-Эмманюэль Шмитт')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'О.Генри')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Александр Сергеевич Пушкин')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Брэм Стокер')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Андрей Андреевич Вознесенскийы')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Николай Надежин')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Анна Яблонская')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Николай Васильевич Мешков')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 2, N'Мажена Садох')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (3, N'Сергей Сергеевич Прокофьев')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Джоаккино Россини')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Иоганн Штраус')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Фридерик Шопен')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Дэниел Роберт Эльфман')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'оркестр GosОrchestra')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Алексей Львович Рыбников')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Шандор Каллош')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Жанна Богусевич')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (3, N'Имре Кальман')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (3, N'Владимир Шаинский')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (3, N'Ирина Губаренко')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (3, N'Вольфганг Амадей Моцарт')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Владимир Амброс')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (3, N'Никита Богословский')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (3, N'Вениамин Ефимович Баснер')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (3, N'Микаэл Лионович Таривердиев')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES (3, N'Антон Танонов')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Игорь Гайденко')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 3, N'Алексей Львович Рыбников')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Оперы и балета')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Музыкальный')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Филармония')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Молодежный')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Драматический')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Авторский')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Детский')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Кукольный')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Школа-театр')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Комедийный')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Театр-кафе')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Сценической анимаци')
INSERT [dbo].[Variants] ([QuestionId], [VariantText]) VALUES ( 4, N'Театр-студия')
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
